filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: istio-system
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: ./charts/istio-system
  version: 1.0.0
  name: istio-system
  values:
  - jx-values.yaml
- chart: jxgh/acme
  version: 0.0.24
  name: acme-jx
  values:
  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
